using SafeTestsets, Test

@time @safetestset "Quality Assurance" include("qa.jl")
@time @safetestset "AutoAbstol" include("autoabstol_tests.jl")
@time @safetestset "TerminateSteadyState tests" include("terminatesteadystate_test.jl")
@time @safetestset "StepsizeLimiter tests" include("stepsizelimiter_tests.jl")
@time @safetestset "Function Calling tests" include("funccall_tests.jl")
@time @safetestset "IndependentlyLinearized tests" include("independentlylinearizedtests.jl")
@time @safetestset "Saving tests" include("saving_tests.jl")
@time @safetestset "PresetTime tests" include("preset_time.jl")
@time @safetestset "Iterative tests" include("iterative_tests.jl")
@time @safetestset "Periodic tests" include("periodic_tests.jl")
@time @safetestset "Manifold tests" include("manifold_tests.jl")
@time @safetestset "Domain tests" include("domain_tests.jl")
@time @safetestset "ProbInts tests" include("probints.jl")
@time @safetestset "Integrating tests" include("integrating_tests.jl")
@time @safetestset "Integrating sum tests" include("integrating_sum_tests.jl")
